In [1]:
import numpy as np

# Creating arrays

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [4]:
m = np.array([[1, 2, 3], [3, 4, 5]])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
m.shape

(2, 3)

In [6]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [8]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [9]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [10]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [14]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.vstack([p, p * 2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.hstack([p, p * 2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [19]:
x

array([1, 2, 3])

In [20]:
y

array([4, 5, 6])

In [21]:
x + y 

array([5, 7, 9])

In [22]:
x * y

array([ 4, 10, 18])

In [23]:
x ** 2

array([1, 4, 9])

In [24]:
x.dot(y)

32

In [25]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [26]:
z.shape

(2, 3)

In [27]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [28]:
z.T.shape

(3, 2)

In [29]:
z.dtype

dtype('int64')

In [30]:
z = z.astype('f')
z.dtype

dtype('float32')

In [31]:
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [32]:
a.sum()

3

In [33]:
a.max()

5

In [34]:
a.min()

-4

In [35]:
a.mean()

0.59999999999999998

In [36]:
a.std()

3.2619012860600183

In [37]:
a.argmax()

4

In [38]:
a.argmin()

0

# Indxing / Slicing

In [39]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [40]:
s[0], s[3], s[0:3]

(0, 9, array([0, 1, 4]))

In [41]:
s[:5], s[:-5]

(array([ 0,  1,  4,  9, 16]), array([ 0,  1,  4,  9, 16, 25, 36, 49]))

In [42]:
s[-1::-2]

array([144, 100,  64,  36,  16,   4,   0])

In [43]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
# second row, second column
r[1, 1]

7

In [45]:
r[3, 3:6]

array([21, 22, 23])

In [46]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [47]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [48]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
r 

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [50]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [51]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [52]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)

[[1 1 1]
 [1 1 1]]


In [53]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)

[[1 1 1]
 [1 1 1]]


# Interating Over Arrays

In [54]:
test = np.random.randint(0, 10, (4, 3))
test

array([[9, 8, 8],
       [3, 4, 2],
       [8, 5, 6],
       [8, 3, 6]])

In [55]:
for row in test:
    print(row)

[9 8 8]
[3 4 2]
[8 5 6]
[8 3 6]


In [56]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 8 8]
row 1 is [3 4 2]
row 2 is [8 5 6]
row 3 is [8 3 6]


In [57]:
test2 = test ** 2
test2

array([[81, 64, 64],
       [ 9, 16,  4],
       [64, 25, 36],
       [64,  9, 36]])

In [58]:
for i, j in zip(test, test2):
    print(i, '+', j, 'is', i + j)

[9 8 8] + [81 64 64] is [90 72 72]
[3 4 2] + [ 9 16  4] is [12 20  6]
[8 5 6] + [64 25 36] is [72 30 42]
[8 3 6] + [64  9 36] is [72 12 42]
